### ISSUE TITLE
[ASA] Continuous integration

### ISSUE THREAD

**Issue by egnaf** [reckue/authorization-service-api#1]
Please connect Travis CI to the project.

#### 1. Add `.travis.yml` to root directory.

**.travis.yml**
```yaml
language: java
jdk: openjdk11
install: true

cache:
  directories:
    - $HOME/.gradle

script:
  - gradle build --refresh-dependencies && cd ..

notifications:
  email:
    recipients:
      - egnaf@yahoo.com
      - hardelele@yahoo.com
    on_success: never
    on_failure: always
```

#### 2. Update `README.md` with the Travis CI build status button.

**README.md**
```md
# note-service-api
[![Build Status](https://travis-ci.com/reckue/authorization-service-api.svg?branch=develop)](https://travis-ci.com/reckue/authorization-service-api)
```

It's all. Good job!
